'use client';

import React from 'react';
import { ComponentItem } from '@/types/component';
import {
  Check, Lock, Bell, Search as SearchIcon, Star, Moon, Command, ArrowRight,
  ShieldCheck, UploadCloud, Smartphone, PhoneCall, Timer, Music, Heart, X, RefreshCw,
  Layers, ChevronRight, HelpCircle, AlertTriangle, Plus, Sliders, Play, Tag, Sparkles,
  BarChart3, TrendingUp, Bot, Mic, Image, Video
} from 'lucide-react';

interface ComponentCardPreviewProps {
  component: ComponentItem;
}

export const ComponentCardPreview: React.FC<ComponentCardPreviewProps> = ({ component }) => {
  const { id, name, category } = component;

  // ===== ACTIONS =====
  if (id === 'ACT-01') return <button className="w-full py-2 bg-blue-600 text-white text-xs font-semibold rounded-xl shadow-xs">Primary Button</button>;
  if (id === 'ACT-02') return <button className="w-full py-2 border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-800 text-gray-700 dark:text-gray-200 text-xs font-semibold rounded-xl">Secondary</button>;
  if (id === 'ACT-03') return <button className="px-3 py-1.5 text-gray-600 dark:text-gray-300 text-xs font-semibold hover:bg-gray-100 dark:hover:bg-gray-800 rounded-lg">Ghost Link →</button>;
  if (id === 'ACT-04') return <button className="w-full py-2 bg-red-600 text-white text-xs font-semibold rounded-xl shadow-xs">Destructive Delete</button>;
  if (id === 'ACT-05') return <button className="w-full py-2 bg-blue-600 text-white text-xs font-semibold rounded-xl flex items-center justify-center gap-2"><RefreshCw className="w-3.5 h-3.5 animate-spin" /> Loading...</button>;
  if (id === 'ACT-06') return <div className="flex gap-2 justify-center"><button className="p-2 rounded-full bg-blue-50 dark:bg-blue-950 text-blue-600 dark:text-blue-400 border"><Bell className="w-4 h-4" /></button><button className="p-2 rounded-full bg-gray-100 dark:bg-gray-800 text-gray-600 dark:text-gray-300"><SearchIcon className="w-4 h-4" /></button></div>;
  if (id === 'ACT-07') return <div className="w-full flex justify-end pr-2"><div className="w-9 h-9 rounded-full bg-blue-600 text-white flex items-center justify-center text-lg font-bold shadow-lg">+</div></div>;
  if (id === 'ACT-08') return <div className="inline-flex rounded-xl border border-gray-300 dark:border-gray-700 overflow-hidden text-xs"><button className="px-3 py-1.5 bg-blue-600 text-white font-bold">Grid</button><button className="px-3 py-1.5 bg-white dark:bg-gray-800 text-gray-600 dark:text-gray-300">List</button></div>;
  if (id === 'ACT-09') return <div className="w-full py-2 bg-gray-900 text-gray-300 text-xs font-mono rounded-xl px-3 flex items-center justify-between border border-gray-700"><span>Search command...</span><kbd className="bg-gray-800 px-1.5 py-0.5 rounded text-[10px]">⌘K</kbd></div>;
  if (id === 'ACT-10') return <div className="flex gap-1 justify-center"><button className="p-1.5 rounded-lg bg-gray-100 dark:bg-gray-800 text-gray-600 dark:text-gray-400 text-xs">✏️</button><button className="p-1.5 rounded-lg bg-gray-100 dark:bg-gray-800 text-gray-600 dark:text-gray-400 text-xs">📋</button><button className="p-1.5 rounded-lg bg-red-50 dark:bg-red-950 text-red-500 text-xs">🗑</button></div>;
  if (id === 'ACT-11') return <div className="w-full py-2 border-2 border-dashed border-gray-300 dark:border-gray-700 text-gray-400 text-xs font-semibold rounded-xl text-center">+ 새 항목 추가</div>;

  // ===== INPUT =====
  if (id === 'INPUT-01') return <input type="text" readOnly value="sample@vibe.ui" className="w-full px-3 py-1.5 text-xs rounded-xl border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-800 text-gray-800 dark:text-gray-200" />;
  if (id === 'INPUT-02') return <div className="w-full p-2 text-[11px] rounded-xl border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-800 text-gray-400">여러 줄 본문 입력 필드...</div>;
  if (id === 'INPUT-03') return <div className="w-full relative"><SearchIcon className="w-3.5 h-3.5 absolute left-3 top-2.5 text-gray-400" /><input type="text" readOnly placeholder="검색..." className="w-full pl-8 pr-3 py-1.5 text-xs rounded-xl border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-800" /></div>;
  if (id === 'INPUT-04') return <div className="flex items-center gap-2 border rounded-xl p-1 bg-white dark:bg-gray-800 text-xs font-bold"><button className="px-2 py-0.5 bg-gray-100 dark:bg-gray-700 rounded">-</button><span>2</span><button className="px-2 py-0.5 bg-gray-100 dark:bg-gray-700 rounded">+</button></div>;
  if (id === 'INPUT-05') return <div className="w-full px-3 py-1.5 border rounded-xl bg-slate-900 text-white text-xs flex justify-between items-center font-mono"><span>React 19 Hooks</span><span className="text-[10px] text-blue-400 font-bold">Auto</span></div>;
  if (id === 'INPUT-06') return <div className="flex gap-1.5 flex-wrap"><span className="px-2 py-0.5 bg-indigo-600/30 text-indigo-300 border border-indigo-500/40 rounded-lg text-[10px] font-bold">#Design</span><span className="px-2 py-0.5 bg-indigo-600/30 text-indigo-300 border border-indigo-500/40 rounded-lg text-[10px] font-bold">#Tailwind</span></div>;
  if (id === 'INPUT-07') return <div className="flex gap-1.5 justify-center">{[9, 0, 7, 2].map((n, i) => <div key={i} className="w-7 h-9 border rounded-lg bg-gray-50 dark:bg-gray-800 flex items-center justify-center font-mono font-bold text-xs text-blue-600 dark:text-blue-400">{n}</div>)}</div>;
  if (id === 'INPUT-08') return <div className="w-full border-2 border-dashed border-gray-300 dark:border-gray-700 rounded-xl py-2 px-3 text-center text-[10px] text-gray-400 flex items-center justify-center gap-1.5"><UploadCloud className="w-4 h-4 text-blue-500" /> 드래그 앤 드롭 파일 업로드</div>;
  if (id === 'INPUT-09') return <div className="w-full h-11 bg-gradient-to-tr from-slate-900 to-blue-900 rounded-xl p-2 text-[10px] text-white font-mono flex items-center justify-between shadow-md"><span>•••• 4532</span><span className="text-amber-400 font-bold">3D Card</span></div>;
  if (id === 'INPUT-10') return <div className="w-full px-3 py-1.5 bg-white dark:bg-gray-800 border rounded-xl text-xs flex items-center justify-between"><span className="text-gray-700 dark:text-gray-300">₩50,000</span><span className="text-[10px] text-gray-400">KRW</span></div>;
  if (id === 'INPUT-11') return <div className="w-full flex items-center gap-2 px-3 py-1.5 border rounded-xl bg-white dark:bg-gray-800"><span className="text-sm">🇰🇷</span><span className="text-xs text-gray-600 dark:text-gray-400">+82 010-1234</span></div>;
  if (id === 'INPUT-12') return <div className="relative w-full"><div className="w-full px-3 py-1.5 border rounded-xl bg-white dark:bg-gray-800 text-xs text-gray-700 dark:text-gray-300">비밀번호</div><span className="absolute right-3 top-2 text-xs text-gray-400">👁</span></div>;
  if (id === 'INPUT-13') return <div className="w-full"><div className="w-full h-1.5 bg-gray-200 dark:bg-gray-700 rounded-full"><div className="w-2/3 h-full bg-blue-500 rounded-full" /></div><div className="flex justify-between text-[10px] text-gray-400 mt-1"><span>약함</span><span className="text-blue-600 font-bold">보통</span><span>강함</span></div></div>;

  // ===== SELECTION =====
  if (id === 'SELECT-01') return <div className="flex items-center gap-2 text-xs font-semibold text-gray-700 dark:text-gray-300"><div className="w-4 h-4 rounded bg-blue-600 text-white flex items-center justify-center text-[10px]"><Check className="w-3 h-3 stroke-[3]" /></div> 이용약관 동의</div>;
  if (id === 'SELECT-02') return <div className="flex items-center gap-2 text-xs font-semibold text-gray-700 dark:text-gray-300"><div className="w-4 h-4 rounded-full border-4 border-blue-600 bg-white" /> 신용카드 결제 선택</div>;
  if (id === 'SELECT-03') return <div className="flex items-center justify-between w-full px-2"><span className="text-xs text-gray-600 dark:text-gray-400 font-medium">알림 수신</span><div className="w-10 h-6 bg-blue-600 rounded-full p-0.5 flex justify-end"><div className="w-5 h-5 bg-white rounded-full shadow-xs" /></div></div>;
  if (id === 'SELECT-04') return <div className="p-1 bg-gray-100 dark:bg-gray-800 rounded-xl flex gap-1 text-xs w-full justify-center"><div className="px-3 py-1 bg-white dark:bg-gray-900 rounded-lg font-bold shadow-xs text-blue-600 dark:text-blue-400">Day</div><div className="px-3 py-1 text-gray-500">Week</div></div>;
  if (id === 'SELECT-05' || id === 'SELECT-06') return <div className="flex gap-1.5 flex-wrap justify-center"><span className="px-2.5 py-1 rounded-full bg-blue-100 dark:bg-blue-950 text-blue-700 dark:text-blue-300 text-xs font-bold border border-blue-300 dark:border-blue-800">#Tailwind</span><span className="px-2.5 py-1 rounded-full bg-gray-100 dark:bg-gray-800 text-gray-600 dark:text-gray-400 text-xs font-semibold">#React</span></div>;
  if (id === 'SELECT-07') return <div className="flex items-center gap-2 p-1 bg-slate-900 text-white rounded-xl border border-gray-700 text-xs font-bold"><button className="px-2 py-0.5 bg-slate-800 rounded">-</button><span>2 개</span><button className="px-2 py-0.5 bg-slate-800 rounded">+</button></div>;
  if (id === 'SELECT-08') return <div className="w-full px-3 flex flex-col gap-1"><div className="flex justify-between text-[10px] text-gray-400"><span>Volume</span><span>70%</span></div><div className="w-full bg-slate-800 h-2 rounded-full"><div className="bg-emerald-500 h-2 rounded-full w-2/3" /></div></div>;
  if (id === 'SELECT-09') return <div className="w-full px-3 py-1.5 bg-slate-900 text-white rounded-xl border border-gray-700 text-xs flex justify-between items-center font-bold"><span>대한민국 (KRW)</span><span>▼</span></div>;
  if (id === 'SELECT-10') return <div className="flex gap-1 text-amber-400 text-base">{[1,2,3,4,5].map(n => <span key={n}>★</span>)}</div>;
  if (id === 'SELECT-11') return <div className="flex gap-1 flex-wrap justify-center">{['서울','부산','제주'].map((v,i) => <span key={v} className={`px-2 py-0.5 text-[10px] rounded-full border font-bold ${i===0?'bg-blue-600 text-white border-blue-600':'bg-white dark:bg-gray-800 text-gray-600 dark:text-gray-400 border-gray-300 dark:border-gray-600'}`}>{v}</span>)}</div>;
  if (id === 'SELECT-12') return <div className="w-full flex flex-col gap-1">{['옵션 A','옵션 B'].map((v,i) => <div key={v} className={`flex items-center gap-2 px-2 py-1 rounded-lg text-xs ${i===0?'bg-blue-50 dark:bg-blue-950 text-blue-700 dark:text-blue-300 font-bold':'text-gray-500'}`}><input type="checkbox" defaultChecked={i===0} readOnly className="w-3 h-3" />{v}</div>)}</div>;
  if (id === 'SELECT-13') return <div className="w-full text-xs space-y-0.5"><div className="flex items-center gap-1 text-gray-700 dark:text-gray-300">▼ <span className="font-semibold">카테고리</span></div><div className="pl-3 flex items-center gap-1 text-blue-600 dark:text-blue-400">▶ UI 컴포넌트</div><div className="pl-6 text-gray-500">버튼</div></div>;

  // ===== DATE & TIME =====
  if (id === 'DATE-01') return <div className="p-2 bg-slate-900 border border-gray-700 text-white rounded-xl text-xs font-bold text-center">2026.09.15 (Calendar)</div>;
  if (id === 'DATE-02') return <div className="p-2 bg-slate-900 border border-gray-700 text-emerald-400 rounded-xl text-xs font-bold text-center">09.10 ➔ 09.18 (8박)</div>;
  if (id === 'DATE-04') return <div className="flex gap-1.5 overflow-hidden w-full justify-center"><div className="w-8 h-11 rounded-lg bg-gray-100 dark:bg-gray-800 flex flex-col items-center justify-center text-[10px] text-gray-500 font-semibold">월5</div><div className="w-8 h-11 rounded-lg bg-blue-600 text-white flex flex-col items-center justify-center text-[10px] font-bold shadow-xs">화6</div><div className="w-8 h-11 rounded-lg bg-gray-100 dark:bg-gray-800 flex flex-col items-center justify-center text-[10px] text-gray-500 font-semibold">수7</div></div>;
  if (id === 'DATE-08') return <div className="px-4 py-2 bg-slate-900 text-blue-400 rounded-xl border border-gray-700 text-xs font-mono font-bold">AM 09 : 30</div>;
  if (id === 'DATE-11') return <div className="w-full px-3 py-1 bg-slate-900 border rounded-xl text-[10px] font-mono text-indigo-300 text-center">09:00 ───[ 10:00 ~ 16:00 ]─── 22:00</div>;
  if (id === 'DATE-12') return <div className="w-full py-1.5 px-3 bg-slate-900 border border-gray-700 rounded-xl text-center font-mono font-bold text-xs text-purple-400">AM 08 : 30 (iOS Wheel)</div>;

  // ===== NAVIGATION =====
  if (id === 'NAV-01') return <div className="w-full py-1.5 bg-slate-950 text-gray-400 rounded-xl border border-gray-800 flex justify-around text-[10px] font-bold"><span>Home</span><span className="text-purple-400">Search</span><span>User</span></div>;
  if (id === 'NAV-02') return <div className="w-full py-1.5 px-3 bg-slate-950 text-white rounded-xl border border-gray-800 flex justify-between text-xs font-bold"><span>Logo</span><span>Navbar Header</span></div>;
  if (id === 'NAV-03') return <div className="flex gap-1 text-[10px] text-gray-400"><span>Home</span>/<span>Products</span>/<span className="text-blue-400 font-bold">UI Kit</span></div>;
  if (id === 'NAV-04') return <div className="flex border-b border-gray-700 text-xs font-bold gap-3"><span className="border-b-2 border-amber-400 text-amber-400 pb-1">Overview</span><span className="text-gray-500">Settings</span></div>;
  if (id === 'NAV-05') return <div className="w-full p-2 bg-slate-900 border text-white rounded-xl text-xs font-bold">Sidebar Drawer Menu</div>;
  if (id === 'NAV-06') return <div className="w-full flex gap-1 justify-center"><div className="px-2 py-1 bg-blue-600 text-white text-[10px] font-bold rounded-lg">1</div><div className="px-2 py-1 text-gray-400 text-[10px]">...</div><div className="px-2 py-1 border text-gray-400 text-[10px] rounded-lg">5</div><div className="px-2 py-1 border text-gray-400 text-[10px] rounded-lg">›</div></div>;
  if (id === 'NAV-07') return <div className="w-full flex gap-2 overflow-hidden"><div className="px-3 py-1.5 bg-gray-100 dark:bg-gray-800 text-gray-600 dark:text-gray-400 rounded-full text-[10px] font-bold flex-shrink-0">← 이전</div><div className="px-3 py-1.5 bg-blue-600 text-white rounded-full text-[10px] font-bold flex-shrink-0">다음 →</div></div>;
  if (id === 'NAV-08') return <div className="px-4 py-1.5 bg-black text-white rounded-full font-bold text-xs flex items-center gap-2 shadow-md"><Music className="w-3.5 h-3.5 text-purple-400" /><span>ETA - NewJeans</span></div>;
  if (id === 'NAV-09') return <div className="w-full bg-slate-900 text-white px-3 py-1.5 rounded-xl border border-gray-700 text-xs"><div className="text-[10px] text-gray-500 mb-0.5">현재 위치</div><div className="font-bold">설정 › 알림 › 앱별 설정</div></div>;
  if (id === 'NAV-10') return <div className="w-full flex flex-col gap-1"><div className="px-3 py-1.5 bg-blue-50 dark:bg-blue-950 text-blue-600 dark:text-blue-400 rounded-lg text-xs font-bold flex items-center gap-2">🏠 Home</div><div className="px-3 py-1.5 text-gray-500 text-xs flex items-center gap-2 pl-6">📁 Products</div></div>;
  if (id === 'NAV-11') return <div className="w-full flex gap-1 text-[10px] font-bold overflow-hidden justify-center"><span className="px-2 py-1 bg-blue-600 text-white rounded-lg">메인</span><span className="px-2 py-1 bg-gray-100 dark:bg-gray-800 text-gray-500 rounded-lg">서비스</span><span className="px-2 py-1 bg-gray-100 dark:bg-gray-800 text-gray-500 rounded-lg">게시판</span></div>;
  if (id === 'NAV-12') return <div className="flex gap-2 p-1 bg-white dark:bg-gray-900 border rounded-xl text-xs"><div className="w-8 h-8 bg-blue-50 dark:bg-blue-950 text-blue-600 rounded-lg flex items-center justify-center text-sm">🏠</div><div className="w-8 h-8 bg-gray-100 dark:bg-gray-800 text-gray-500 rounded-lg flex items-center justify-center text-sm">⚙️</div><div className="w-8 h-8 bg-gray-100 dark:bg-gray-800 text-gray-500 rounded-lg flex items-center justify-center text-sm">👤</div></div>;
  if (id === 'NAV-13') return <div className="flex border-b border-gray-200 dark:border-gray-700 text-xs font-bold gap-3"><span className="border-b-2 border-blue-600 text-blue-600 pb-1 flex items-center gap-1">받은함 <span className="bg-red-500 text-white text-[9px] px-1 rounded-full">3</span></span><span className="text-gray-500">보낸함</span></div>;

  // ===== OVERLAY =====
  if (id === 'OVER-01') return <div className="w-full bg-gray-900 text-white rounded-xl p-2 text-center text-xs font-bold border border-gray-700 shadow-md">Modal Dialog Window</div>;
  if (id === 'OVER-02' || id === 'OVER-04') return <div className="px-3 py-1 bg-gray-800 text-white text-[10px] rounded-lg border border-gray-700">Tooltip 말풍선</div>;
  if (id === 'OVER-03') return <div className="w-full h-11 bg-gray-100 dark:bg-gray-800 rounded-t-xl flex flex-col items-center justify-start pt-1 border-t-2 border-blue-500"><div className="w-6 h-1 bg-gray-400 rounded-full" /></div>;
  if (id === 'OVER-05') return <div className="w-full p-2 bg-slate-900 text-white rounded-t-xl border-t border-rose-500 text-xs font-bold text-center">Action Sheet</div>;
  if (id === 'OVER-06') return <div className="w-full p-1.5 bg-amber-500/20 text-amber-300 rounded-xl text-[10px] font-bold text-center border border-amber-500/30">시스템 점검 공지 알림 바</div>;
  if (id === 'OVER-07') return <div className="relative w-full"><div className="w-full h-8 bg-gray-200 dark:bg-gray-700 rounded-xl" /><div className="absolute top-1 left-2 right-2 bg-white dark:bg-gray-800 rounded-lg p-1 shadow-sm text-[10px] text-gray-600 dark:text-gray-400">Context Menu 항목들...</div></div>;
  if (id === 'OVER-08') return <div className="w-full p-2 bg-white dark:bg-gray-800 border rounded-xl shadow-lg text-[10px] space-y-1"><div className="font-bold text-gray-700 dark:text-gray-300">알림</div><div className="text-gray-500">확인하시겠습니까?</div><div className="flex gap-1 justify-end"><span className="px-2 py-0.5 bg-blue-600 text-white rounded text-[9px]">확인</span></div></div>;
  if (id === 'OVER-09') return <div className="w-full flex items-center justify-center h-10"><div className="w-6 h-6 rounded-full border-4 border-blue-500 border-t-transparent animate-spin" /></div>;
  if (id === 'OVER-10') return <div className="w-full p-2 bg-green-50 dark:bg-green-950 border border-green-300 dark:border-green-800 rounded-xl text-[10px] text-green-700 dark:text-green-400 font-bold text-center">✓ 저장되었습니다</div>;
  if (id === 'OVERLAY-11') return <div className="w-full bg-white dark:bg-gray-900 rounded-t-2xl border-t pt-2 pb-1"><div className="w-8 h-1 bg-gray-300 rounded-full mx-auto mb-2" /><div className="text-xs font-bold text-center text-gray-700 dark:text-gray-300 pb-2">Bottom Sheet</div></div>;
  if (id === 'OVERLAY-12') return <div className="w-full flex justify-end"><div className="w-1/2 bg-white dark:bg-gray-800 border-l border-gray-200 dark:border-gray-700 p-2 rounded-r-xl shadow-lg"><div className="text-[10px] font-bold text-gray-700 dark:text-gray-300 mb-1">상세 패널</div><div className="h-4 bg-gray-100 dark:bg-gray-700 rounded w-full" /></div></div>;

  // ===== LISTS & CARDS =====
  if (id === 'LIST-01') return <div className="p-2 border rounded-xl bg-slate-900 text-white text-xs font-bold w-full">Basic Feed Card</div>;
  if (id === 'LIST-02') return <div className="w-full h-12 bg-gradient-to-r from-blue-900 to-indigo-900 rounded-xl p-2 text-white font-bold text-xs flex items-end">Image Product Card</div>;
  if (id === 'LIST-03') return <div className="w-full p-2 bg-slate-900 border text-blue-400 text-xs font-bold rounded-xl text-center">Carousel Banner (1/3)</div>;
  if (id === 'LIST-04') return <div className="w-full p-1 bg-slate-900 text-[10px] text-gray-300 border rounded-xl font-mono text-center">Table Grid Header | Data</div>;
  if (id === 'LIST-05') return <div className="w-full flex items-center gap-2 p-2 bg-white dark:bg-gray-800 border rounded-xl"><div className="w-6 h-6 bg-blue-100 dark:bg-blue-950 rounded-full flex items-center justify-center text-xs">👤</div><div className="flex-1 text-xs text-gray-700 dark:text-gray-300 font-semibold">사용자 이름</div><span className="text-[10px] text-gray-400">방금 전</span></div>;
  if (id === 'LIST-06') return <div className="w-full p-2 bg-slate-900 border-l-4 border-l-red-500 text-white text-xs font-bold rounded-xl">Swipe to Delete Item</div>;
  if (id === 'LIST-07') return <div className="w-full grid grid-cols-2 gap-1"><div className="bg-blue-600 rounded-lg p-2 text-white text-[10px] font-bold col-span-2">Featured</div><div className="bg-gray-100 dark:bg-gray-800 rounded-lg p-2 text-[10px] text-gray-500">Item</div><div className="bg-gray-100 dark:bg-gray-800 rounded-lg p-2 text-[10px] text-gray-500">Item</div></div>;
  if (id === 'LIST-08') return <div className="flex gap-2 w-full overflow-hidden"><div className="flex-shrink-0 w-16 h-16 bg-gradient-to-br from-purple-400 to-pink-400 rounded-xl" /><div className="text-xs"><div className="font-bold text-gray-800 dark:text-gray-200">타이틀</div><div className="text-gray-500 text-[10px]">설명 텍스트</div></div></div>;
  if (id === 'LIST-11') return <div className="w-24 h-12 bg-gradient-to-tr from-purple-600 to-pink-600 rounded-xl text-white text-[10px] font-bold flex items-center justify-center shadow-md rotate-[-3deg]">Swipe Card Stack</div>;
  if (id === 'LISTS-11') return <div className="w-full border rounded-xl overflow-hidden text-[10px]"><div className="bg-gray-50 dark:bg-gray-800 px-2 py-1 flex gap-3 border-b font-bold text-gray-600 dark:text-gray-400"><span>이름 ▲</span><span>상태</span><span>날짜</span></div><div className="px-2 py-1 text-gray-700 dark:text-gray-300 flex gap-3"><span>김철수</span><span className="text-green-600">활성</span><span>09.08</span></div></div>;

  // ===== SEARCH & FILTER =====
  if (id === 'SEARCH-01') return <div className="w-full px-3 py-1.5 bg-slate-900 border border-gray-700 text-white text-xs rounded-xl flex items-center gap-1.5"><SearchIcon className="w-3.5 h-3.5 text-blue-400" /><span>통합 검색 바</span></div>;
  if (id === 'SEARCH-02') return <div className="flex gap-1"><span className="px-2 py-0.5 bg-blue-600/30 text-blue-300 rounded-full text-[10px] font-bold">Category: Actions ✕</span></div>;
  if (id === 'SEARCH-03') return <div className="px-3 py-1.5 bg-slate-900 text-white text-xs rounded-xl border border-gray-700 font-bold">정렬: 최신순 ▼</div>;
  if (id === 'SEARCH-04') return <div className="w-full p-2 bg-slate-900 text-emerald-400 text-xs font-bold border rounded-xl text-center">Filter Options Panel</div>;

  // ===== FEEDBACK & STATES =====
  if (id === 'FEED-01') return <div className="flex items-center justify-center w-full h-10"><div className="w-6 h-6 rounded-full border-4 border-blue-500 border-t-transparent animate-spin" /></div>;
  if (id === 'FEED-02') return <div className="w-full p-2 bg-gray-900 text-white text-xs font-bold rounded-xl border-l-4 border-l-green-500 flex items-center gap-2"><span>✓</span> 저장 완료!</div>;
  if (id === 'FEED-03') return <div className="w-full px-2"><div className="w-full bg-gray-200 dark:bg-gray-700 h-2 rounded-full"><div className="w-2/3 h-2 bg-blue-500 rounded-full" /></div><div className="text-[10px] text-gray-400 mt-1 text-right">67%</div></div>;
  if (id === 'FEED-04') return <div className="w-full space-y-1.5"><div className="h-3 bg-gray-200 dark:bg-gray-700 rounded-full animate-pulse" /><div className="h-3 bg-gray-200 dark:bg-gray-700 rounded-full animate-pulse w-3/4" /><div className="h-3 bg-gray-200 dark:bg-gray-700 rounded-full animate-pulse w-1/2" /></div>;
  if (id === 'FEED-05') return <div className="w-full text-center text-gray-400 py-2"><div className="text-2xl mb-1">📭</div><div className="text-[10px] font-semibold">결과 없음</div></div>;
  if (id === 'FEED-06') return <div className="w-full p-2 bg-yellow-50 dark:bg-yellow-950 border border-yellow-300 dark:border-yellow-800 rounded-xl text-[10px] text-yellow-700 dark:text-yellow-400 font-bold">⚠️ 주의 메시지</div>;
  if (id === 'FEED-07') return <div className="w-full p-2 bg-red-50 dark:bg-red-950 border border-red-300 dark:border-red-800 rounded-xl text-[10px] text-red-700 dark:text-red-400 font-bold">❌ 오류가 발생했습니다</div>;
  if (id === 'FEED-08') return <div className="w-full flex items-center gap-2 p-2 bg-gray-50 dark:bg-gray-800 border rounded-xl"><div className="w-5 h-5 bg-blue-100 dark:bg-blue-950 rounded-full flex items-center justify-center text-xs">🔔</div><div className="flex-1 text-[10px] font-semibold text-gray-700 dark:text-gray-300">인라인 알림 배너</div></div>;
  if (id === 'FEED-09') return <div className="w-full flex items-center gap-2 p-2 bg-blue-50 dark:bg-blue-950 border border-blue-200 dark:border-blue-900 rounded-xl"><div className="text-sm">ℹ️</div><div className="text-[10px] text-blue-700 dark:text-blue-400 font-semibold">안내 툴팁 카드</div></div>;
  if (id === 'FEED-10') return <div className="w-full p-2 border rounded-xl bg-white dark:bg-gray-800 shadow-sm text-[10px]"><div className="flex gap-2"><div className="text-xs">⭐⭐⭐⭐⭐</div></div><div className="text-gray-600 dark:text-gray-400 mt-1">사용자 리뷰 카드</div></div>;
  if (id === 'FEED-11') return <div className="w-full"><div className="h-0.5 bg-gray-100 dark:bg-gray-800 w-full relative"><div className="absolute top-0 left-0 w-3/4 h-full bg-blue-600 animate-pulse" /></div><div className="text-[10px] text-gray-400 mt-1 text-center">페이지 로딩...</div></div>;
  if (id === 'FEED-12') return <div className="flex flex-col items-center"><svg width="40" height="40" viewBox="0 0 80 80"><circle cx="40" cy="40" r="36" fill="none" stroke="#22c55e" strokeWidth="4" /><path d="M 24 40 L 36 52 L 58 28" fill="none" stroke="#22c55e" strokeWidth="4" strokeLinecap="round" strokeLinejoin="round" /></svg><div className="text-[10px] text-green-600 font-bold mt-1">완료!</div></div>;
  if (id === 'FEED-13') return <div className="w-full text-center py-2 text-gray-400"><div className="text-2xl mb-1">📬</div><div className="text-[10px] font-semibold">Empty State</div></div>;

  // ===== GESTURE =====
  if (id === 'GEST-01') return <div className="w-full p-2 bg-purple-950/40 text-purple-300 border border-purple-800/50 rounded-xl text-[10px] font-bold text-center">Long Press 1s Hold</div>;
  if (id === 'GEST-02') return <div className="w-full p-2 bg-blue-950/40 text-blue-300 border border-blue-800/50 rounded-xl text-[10px] font-bold text-center">Pinch Zoom 150%</div>;
  if (id === 'GEST-03') return <div className="w-full p-2 bg-pink-950/40 text-pink-300 border border-pink-800/50 rounded-xl text-[10px] font-bold text-center flex items-center justify-center gap-1">Double Tap ❤️ 128</div>;
  if (id === 'GEST-04') return <div className="w-full p-2 bg-slate-900 border text-blue-400 text-[10px] font-bold rounded-xl text-center">Pull Down Refresh ↓</div>;
  if (id === 'GEST-05') return <div className="w-full p-2 bg-slate-900 border text-orange-400 text-[10px] font-bold rounded-xl text-center flex items-center justify-center gap-1">← Swipe 아카이브 →</div>;
  if (id === 'GEST-06') return <div className="relative w-full overflow-hidden rounded-xl"><div className="bg-green-500/20 absolute inset-0 flex items-center pl-3 text-green-500 text-[10px] font-bold">📦 아카이브</div><div className="relative bg-white dark:bg-gray-800 px-3 py-2 ml-10 rounded-r-xl text-xs text-gray-700 dark:text-gray-300 font-semibold border-l">← 스와이프</div></div>;
  if (id === 'GEST-07') return <div className="w-full flex flex-col items-center gap-1"><div className="w-4 h-4 rounded-full border-2 border-blue-500 border-t-transparent animate-spin" /><div className="text-[10px] text-gray-400">당겨서 새로고침</div></div>;
  if (id === 'GEST-08') return <div className="w-full p-2 bg-white dark:bg-gray-800 border rounded-xl shadow-md text-[10px]"><div className="font-bold text-gray-700 dark:text-gray-300 mb-1">길게 누르기</div><div className="flex gap-1"><span className="px-2 py-0.5 bg-gray-100 dark:bg-gray-700 rounded text-gray-600 dark:text-gray-400">복사</span><span className="px-2 py-0.5 bg-gray-100 dark:bg-gray-700 rounded text-gray-600 dark:text-gray-400">공유</span><span className="px-2 py-0.5 bg-red-50 dark:bg-red-950 rounded text-red-500">삭제</span></div></div>;

  // ===== MOTION =====
  if (id === 'MOTION-01') return <div className="w-full py-1.5 px-3 bg-blue-600 text-white rounded-xl text-[10px] font-bold text-center shadow-md">Click Scale 0.92</div>;
  if (id === 'MOTION-02') return <div className="flex gap-2 bg-slate-900 p-1 rounded-xl text-[10px] text-amber-400 font-bold border"><span className="bg-amber-500 text-black px-2 py-0.5 rounded-lg">Tab 1</span><span>Tab 2</span></div>;
  if (id === 'MOTION-03') return <div className="w-full flex flex-col gap-1">{[1,2,3].map(i => <div key={i} style={{opacity: 0.3 + i*0.3, transform: `translateY(${(3-i)*4}px)`}} className="h-2 bg-blue-500 rounded-full transition-all" />)}</div>;
  if (id === 'MOTION-04') return <div className="w-full text-center"><div className="inline-block text-2xl animate-bounce">🪄</div><div className="text-[10px] text-gray-500 mt-1">Micro Animation</div></div>;
  if (id === 'MOTION-05') return <div className="w-full px-3 py-2 bg-white dark:bg-gray-800 border rounded-xl text-[10px] flex items-center gap-2"><div className="w-3 h-3 rounded-full bg-green-500" /><span className="text-gray-600 dark:text-gray-400">상태 전환 모션</span></div>;
  if (id === 'MOTION-06') return <div className="w-full space-y-1">{[0.4,0.6,0.8].map((w,i) => <div key={i} style={{width:`${w*100}%`}} className="h-2 bg-indigo-400 rounded-full opacity-75" />)}</div>;
  if (id === 'MOTION-07') return <div className="w-full text-center text-xs text-gray-500"><span className="text-lg">✨</span><div className="text-[10px] mt-0.5">Ripple Effect</div></div>;
  if (id === 'MOTION-08') return <div className="grid grid-cols-3 gap-1 w-full"><div className="col-span-2 p-2 bg-slate-900 text-white rounded-lg text-[10px] font-bold">Bento Core</div><div className="p-2 bg-slate-800 text-gray-300 rounded-lg text-[10px]">Side</div></div>;
  if (id === 'MOTION-09') return <div className="text-xl font-mono font-extrabold text-blue-600 dark:text-blue-400 flex items-center gap-1">$ <span className="text-gray-900 dark:text-white">128,450</span></div>;
  if (id === 'MOTION-10') return <div className="w-full py-1 px-2 bg-pink-950/40 border border-pink-800/50 rounded-xl text-[10px] text-pink-300 font-bold overflow-hidden whitespace-nowrap">Infinite Marquee Scrolling...</div>;
  if (id === 'MOTION-11') return <div className="flex gap-2 p-1.5 bg-black rounded-2xl border text-xs text-indigo-400 justify-center"><span>Home</span><span className="text-white font-bold scale-125">Search</span><span>User</span></div>;
  if (id === 'MOTION-12') return <div className="w-full relative h-8"><div className="absolute inset-0 bg-gray-200 dark:bg-gray-700 rounded-xl animate-pulse" /><div className="absolute inset-0 bg-white dark:bg-gray-800 rounded-xl opacity-0 animate-ping" /><div className="relative text-[10px] text-gray-400 text-center pt-2">스켈레톤 → 컨텐츠</div></div>;
  if (id === 'MOTION-13') return <div className="w-full flex flex-col gap-1">{[0,1,2].map(i => <div key={i} style={{animationDelay:`${i*100}ms`}} className="h-2 bg-blue-400/60 rounded-full animate-pulse" />)}</div>;
  if (id === 'MOTION-14') return <div className="w-full overflow-hidden rounded-xl"><div className="px-3 py-2 bg-blue-600 text-white text-[10px] font-bold animate-pulse">→ 페이지 전환 슬라이드</div></div>;

  // ===== PATTERNS =====
  if (id === 'PATTERNS-01') return <div className="w-full p-2 bg-slate-900 border text-amber-400 text-xs font-bold rounded-xl text-center">Step 1 ➔ Step 2 ➔ Step 3</div>;
  if (id === 'PATTERNS-02') return <div className="w-full p-2 bg-purple-950/40 text-purple-300 border border-purple-800/50 rounded-xl text-[10px] font-bold text-center">Onboarding Guide (1/3)</div>;
  if (id === 'PATTERNS-03') return <div className="w-full p-2 bg-emerald-950/40 text-emerald-300 border border-emerald-800/50 rounded-xl text-[10px] font-bold text-center">Checkout ₩29,000</div>;
  if (id === 'PATTERNS-04') return <div className="w-full p-2 bg-slate-900 border text-gray-300 rounded-xl text-[10px] font-bold text-center">알림 설정 패널</div>;
  if (id === 'PATTERNS-05') return <div className="w-full p-2 bg-slate-900 border text-blue-400 rounded-xl text-[10px] font-bold text-center">다크/라이트 테마 ☀️🌙</div>;
  if (id === 'PATTERNS-06') return <div className="w-full p-2 bg-orange-950/40 text-orange-300 border border-orange-800/40 rounded-xl text-[10px] font-bold text-center">실행 취소 스낵바</div>;
  if (id === 'PATTERNS-07') return <div className="w-full flex flex-col gap-1 p-1"><div className="flex items-center gap-1 text-[10px]"><input type="checkbox" defaultChecked className="w-3 h-3" /><span className="text-gray-600 dark:text-gray-400">권한 동의 체크</span></div><div className="flex gap-1 text-[10px] justify-end"><span className="px-2 py-0.5 bg-blue-600 text-white rounded">동의</span><span className="px-2 py-0.5 border rounded text-gray-400">거부</span></div></div>;
  if (id === 'PATTERNS-08') return <div className="w-full p-2 bg-gradient-to-r from-blue-600 to-purple-600 text-white rounded-xl text-[10px] font-bold text-center">🎁 프로모션 배너</div>;
  if (id === 'PATTERNS-09') return <div className="w-full p-2 bg-slate-900 border text-cyan-400 rounded-xl text-[10px] font-bold text-center">쿠키 동의 배너</div>;
  if (id === 'PATTERNS-10') return <div className="w-full p-2 bg-slate-900 border text-violet-400 rounded-xl text-[10px] font-bold text-center">소셜 공유 시트</div>;
  if (id === 'PATTERNS-11') return <div className="w-full p-2 bg-white dark:bg-gray-800 border rounded-xl text-[10px]"><div className="font-bold text-gray-700 dark:text-gray-300 mb-1">팀원 초대</div><div className="flex gap-1"><input readOnly value="이메일 입력" className="flex-1 px-2 py-0.5 border rounded text-[9px] bg-gray-50 dark:bg-gray-700" /><span className="px-2 py-0.5 bg-blue-600 text-white rounded text-[9px]">초대</span></div></div>;
  if (id === 'PATTERNS-12') return <div className="w-full p-2 bg-white dark:bg-gray-800 border rounded-xl text-center text-[10px] relative overflow-hidden"><div className="blur-sm text-gray-400 mb-1">프리미엄 기능</div><div className="text-sm">🔒</div><div className="text-[9px] font-bold text-blue-600">Pro 업그레이드</div></div>;
  if (id === 'PATTERNS-13') return <div className="w-full bg-gray-900 border border-gray-700 rounded-xl p-2 text-xs"><div className="flex items-center gap-1.5 mb-1"><SearchIcon className="w-3 h-3 text-gray-400" /><span className="text-gray-400">명령어 검색...</span></div><div className="text-[10px] text-blue-400">⚡ 설정으로 이동</div></div>;
  if (id === 'PATTERNS-14') return <div className="w-full text-center p-2"><div className="text-xl mb-1">⭐⭐⭐⭐⭐</div><div className="text-[10px] text-gray-500 font-semibold">앱이 마음에 드시나요?</div></div>;
  if (id === 'PATTERNS-15') return <div className="w-full h-12 bg-gradient-to-br from-blue-600 to-indigo-700 rounded-xl p-2 text-white text-[10px] font-bold flex items-end justify-between"><span>1/3</span><div className="flex gap-1">{[0,1,2].map(i => <div key={i} className={`rounded-full ${i===0?'w-4 h-1.5 bg-white':'w-1.5 h-1.5 bg-white/40'}`} />)}</div></div>;
  if (id === 'PATTERNS-16') return <div className="w-full bg-gray-900 text-white rounded-xl p-2 text-[10px]"><div className="font-bold mb-1">💡 새 기능 안내</div><div className="text-gray-400">2/4 단계</div><div className="flex gap-1 mt-1 justify-end"><span className="px-2 py-0.5 bg-blue-600 rounded text-[9px]">다음 →</span></div></div>;
  if (id === 'PATTERNS-17') return <div className="w-full bg-white dark:bg-gray-800 border rounded-xl p-2 text-center text-[10px]"><div className="text-lg">🚀</div><div className="font-bold text-gray-700 dark:text-gray-300">v2.0 업데이트</div><div className="px-2 py-0.5 bg-blue-600 text-white rounded-lg mt-1 text-[9px]">지금 업데이트</div></div>;

  // ===== DATA DISPLAY =====
  if (id === 'DISPLAY-01') return <div className="flex gap-1.5 justify-center"><span className="px-2 py-0.5 bg-blue-100 dark:bg-blue-950 text-blue-700 dark:text-blue-300 text-[10px] font-bold rounded-full border border-blue-300 dark:border-blue-800">NEW</span><span className="px-2 py-0.5 bg-green-100 dark:bg-green-950 text-green-700 dark:text-green-300 text-[10px] font-bold rounded-full border border-green-300 dark:border-green-800">✓ 완료</span></div>;
  if (id === 'DISPLAY-02') return <div className="flex items-center gap-2"><div className="w-8 h-8 rounded-full bg-gradient-to-tr from-blue-500 to-purple-500 flex items-center justify-center text-white text-xs font-bold">김</div><div className="text-xs text-gray-700 dark:text-gray-300 font-semibold">김철수</div></div>;
  if (id === 'DISPLAY-03') return <div className="w-full p-2 bg-white dark:bg-gray-800 border rounded-xl text-[10px]"><div className="text-xs font-extrabold text-blue-600">₩128,450</div><div className="flex items-center gap-1 text-green-600 text-[9px] font-bold"><span>▲</span><span>12.3%</span></div></div>;
  if (id === 'DISPLAY-04') return <div className="flex flex-col items-center"><div className="relative w-10 h-10"><svg viewBox="0 0 36 36" className="w-full h-full -rotate-90"><circle cx="18" cy="18" r="15" fill="none" stroke="#e5e7eb" strokeWidth="4" /><circle cx="18" cy="18" r="15" fill="none" stroke="#3b82f6" strokeWidth="4" strokeDasharray="60 40" /></svg><div className="absolute inset-0 flex items-center justify-center text-[10px] font-bold text-blue-600">60%</div></div></div>;
  if (id === 'DISPLAY-05') return <div className="w-full flex flex-col gap-1.5"><div className="flex items-center gap-2 text-[10px]"><div className="h-2 flex-1 bg-gray-200 dark:bg-gray-700 rounded-full overflow-hidden"><div className="w-3/4 h-full bg-blue-500 rounded-full" /></div><span className="text-gray-500 w-6">75%</span></div><div className="flex items-center gap-2 text-[10px]"><div className="h-2 flex-1 bg-gray-200 dark:bg-gray-700 rounded-full overflow-hidden"><div className="w-2/5 h-full bg-green-500 rounded-full" /></div><span className="text-gray-500 w-6">40%</span></div></div>;
  if (id === 'DISPLAY-06') return <div className="w-full flex flex-col gap-1 text-[10px]"><div className="flex gap-2 items-center"><div className="w-2 h-2 rounded-full bg-blue-500 flex-shrink-0 mt-0.5" /><div><div className="font-semibold text-gray-700 dark:text-gray-300">이벤트 발생</div><div className="text-gray-400">10:30 AM</div></div></div><div className="ml-3 w-0.5 h-3 bg-gray-200 dark:bg-gray-700" /></div>;
  if (id === 'DISPLAY-07') return <svg width="100%" height="32"><polyline points="0,28 20,20 40,24 60,10 80,18 100%,8" fill="none" stroke="#3b82f6" strokeWidth="2" strokeLinecap="round" /></svg>;
  if (id === 'DISPLAY-08') return <div className="w-full border rounded-xl overflow-hidden text-[10px]"><div className="grid grid-cols-3 bg-gray-50 dark:bg-gray-800 px-2 py-1 font-bold text-gray-600 dark:text-gray-400"><span>이름</span><span>값</span><span>편집</span></div><div className="grid grid-cols-3 px-2 py-1 text-gray-700 dark:text-gray-300"><span>항목1</span><span className="text-blue-600">편집중</span><span>✏️</span></div></div>;
  if (id === 'DISPLAY-09') return <div className="w-full flex flex-col items-center"><div className="w-8 h-8 rounded-full bg-gradient-to-tr from-blue-500 to-indigo-500 flex items-center justify-center text-white text-xs font-bold border-2 border-white shadow-sm">A</div><div className="text-[10px] text-gray-600 dark:text-gray-400 mt-1 font-semibold">홍길동</div></div>;
  if (id === 'DISPLAY-10') return <div className="flex flex-wrap gap-1 justify-center">{['React','TypeScript','Next'].map(t => <span key={t} className="px-1.5 py-0.5 bg-gray-100 dark:bg-gray-800 text-gray-600 dark:text-gray-400 text-[9px] font-bold rounded-full border">{t}</span>)}</div>;
  if (id === 'DISPLAY-11') return <div className="grid gap-0.5" style={{gridTemplateColumns:'repeat(10,1fr)'}}>{Array.from({length:70},(_,i)=><div key={i} className={`aspect-square rounded-sm ${['bg-gray-100 dark:bg-gray-800','bg-green-200','bg-green-400','bg-green-600','bg-green-800'][Math.floor(Math.random()*5)]}`} />)}</div>;
  if (id === 'DISPLAY-12') return <div className="w-full border rounded-xl overflow-hidden text-[10px]"><div className="grid grid-cols-3 bg-gray-50 dark:bg-gray-800 px-2 py-1 font-bold text-gray-500"><span>기능</span><span className="text-center">Free</span><span className="text-center text-blue-600">Pro</span></div><div className="grid grid-cols-3 px-2 py-1 border-t text-gray-700 dark:text-gray-300"><span>API 접근</span><span className="text-center text-gray-300">—</span><span className="text-center text-green-600">✓</span></div></div>;
  if (id === 'DISPLAY-13') return <div className="w-full p-2 bg-white dark:bg-gray-800 border rounded-xl"><div className="text-[10px] text-gray-500">월 매출</div><div className="text-lg font-extrabold text-gray-900 dark:text-white">₩12.4M</div><div className="text-[10px] text-green-600 font-bold">▲ 8.2% 전월 대비</div></div>;
  if (id === 'DISPLAY-14') return <div className="w-full space-y-1.5"><div className="flex items-center gap-2 text-[10px]"><div className="w-5 h-5 rounded-full bg-blue-500 flex items-center justify-center text-white text-[9px]">김</div><span className="text-gray-600 dark:text-gray-400"><b>김철수</b>가 수정</span><span className="text-[9px] text-green-500 font-bold">LIVE</span></div><div className="flex items-center gap-2 text-[10px]"><div className="w-5 h-5 rounded-full bg-purple-500 flex items-center justify-center text-white text-[9px]">박</div><span className="text-gray-600 dark:text-gray-400"><b>박영희</b>가 추가</span></div></div>;

  // ===== LAYOUT =====
  if (id === 'LAYOUT-01') return <div className="grid grid-cols-3 gap-1 w-full"><div className="col-span-2 bg-blue-100 dark:bg-blue-950 rounded-lg p-2 text-[10px] font-bold text-blue-700 dark:text-blue-300">Main</div><div className="bg-gray-100 dark:bg-gray-800 rounded-lg p-2 text-[10px] text-gray-500">Side</div><div className="bg-gray-100 dark:bg-gray-800 rounded-lg p-2 text-[10px] text-gray-500">A</div><div className="bg-gray-100 dark:bg-gray-800 rounded-lg p-2 text-[10px] text-gray-500">B</div></div>;
  if (id === 'LAYOUT-02') return <div className="w-full flex gap-1"><div className="w-1/3 h-16 bg-gray-100 dark:bg-gray-800 rounded-lg flex items-center justify-center text-[10px] text-gray-500 border-r-2 border-dashed border-gray-300 dark:border-gray-600">좌</div><div className="flex-1 h-16 bg-blue-50 dark:bg-blue-950 rounded-lg flex items-center justify-center text-[10px] text-blue-600 font-bold">분할 뷰</div></div>;
  if (id === 'LAYOUT-03') return <div className="w-full space-y-1"><div className="text-[10px] text-gray-500 flex justify-between"><span>항목 1</span><span>항목 2</span><span>항목 3</span></div><div className="text-[10px] text-blue-500 text-center">∞ 무한 스크롤</div></div>;
  if (id === 'LAYOUT-04') return <div className="grid gap-1 w-full" style={{gridTemplateColumns:'repeat(3,1fr)'}}><div style={{gridRow:'span 2'}} className="bg-blue-100 dark:bg-blue-950 rounded-lg" /><div className="bg-gray-100 dark:bg-gray-800 rounded-lg h-5" /><div className="bg-gray-100 dark:bg-gray-800 rounded-lg h-5" /><div style={{gridColumn:'span 2'}} className="bg-purple-100 dark:bg-purple-950 rounded-lg h-5" /></div>;
  if (id === 'LAYOUT-05') return <div className="w-full flex justify-center"><div className="inline-flex items-center gap-1 px-3 py-1.5 bg-gray-900 text-white rounded-xl text-[10px] font-bold shadow-lg"><span>B</span><span className="italic">I</span><span>🔗</span><span>💬</span></div></div>;
  if (id === 'LAYOUT-06') return <div className="w-full grid grid-cols-2 gap-2 text-[10px] text-gray-600 dark:text-gray-400 leading-relaxed"><div>멀티 컬럼 레이아웃 텍스트 신문처럼...</div><div>두 번째 컬럼 내용이 여기에 표시됩니다</div></div>;
  if (id === 'LAYOUT-07') return <div className="w-full flex gap-1.5 overflow-hidden"><div className="flex-shrink-0 w-20 bg-yellow-50 dark:bg-yellow-950 border border-yellow-200 dark:border-yellow-900 rounded-xl p-1.5 text-[10px]"><div className="font-bold text-yellow-700 dark:text-yellow-400 mb-1">진행중 2</div><div className="bg-white dark:bg-gray-800 rounded-lg p-1 text-gray-600 dark:text-gray-400 mb-1">Task A</div><div className="bg-white dark:bg-gray-800 rounded-lg p-1 text-gray-600 dark:text-gray-400">Task B</div></div><div className="flex-shrink-0 w-20 bg-green-50 dark:bg-green-950 border border-green-200 dark:border-green-900 rounded-xl p-1.5 text-[10px]"><div className="font-bold text-green-700 dark:text-green-400 mb-1">완료 1</div><div className="bg-white dark:bg-gray-800 rounded-lg p-1 text-gray-600 dark:text-gray-400">Task C</div></div></div>;

  // ===== COMMUNICATION =====
  if (id === 'COMM-01') return <div className="flex gap-2 items-end"><div className="bg-gray-100 dark:bg-gray-800 rounded-2xl rounded-bl-sm px-3 py-1.5 text-xs text-gray-700 dark:text-gray-300">안녕하세요 👋</div><div className="bg-blue-600 rounded-2xl rounded-br-sm px-3 py-1.5 text-xs text-white ml-auto">반갑습니다!</div></div>;
  if (id === 'COMM-02') return <div className="relative w-8 h-8"><Bell className="w-full h-full text-gray-400" /><span className="absolute -top-1 -right-1 bg-red-500 text-white text-[9px] font-bold w-4 h-4 rounded-full flex items-center justify-center">3</span></div>;
  if (id === 'COMM-03') return <div className="flex gap-1 items-center"><div className="flex gap-0.5">{[0,1,2].map(i => <span key={i} style={{animationDelay:`${i*150}ms`}} className="w-1.5 h-1.5 bg-gray-400 rounded-full animate-bounce" />)}</div><span className="text-[10px] text-gray-400 ml-1">입력 중...</span></div>;
  if (id === 'COMM-04') return <div className="w-full flex flex-col gap-1"><div className="bg-gray-100 dark:bg-gray-800 rounded-xl p-2 text-[10px] text-gray-600 dark:text-gray-400">원본 댓글 내용</div><div className="ml-4 bg-blue-50 dark:bg-blue-950 rounded-xl p-2 text-[10px] text-blue-700 dark:text-blue-300 border-l-2 border-blue-400">└ 답글 내용</div></div>;
  if (id === 'COMM-05') return <div className="flex gap-1.5 flex-wrap justify-center">{['👍','❤️','😂','😮'].map(e => <button key={e} className="px-2 py-0.5 bg-gray-100 dark:bg-gray-800 rounded-full text-xs border">{e}</button>)}</div>;
  if (id === 'COMM-06') return <div className="w-full flex items-center gap-2 p-2 bg-gray-50 dark:bg-gray-800 border rounded-xl"><div className="w-5 h-5 rounded-full bg-green-500 flex items-center justify-center text-white text-[9px] flex-shrink-0">●</div><div className="text-[10px] font-semibold text-gray-700 dark:text-gray-300">온라인 상태 표시</div></div>;
  if (id === 'COMM-07') return <div className="w-full p-2 bg-blue-50 dark:bg-blue-950 border border-blue-200 dark:border-blue-900 rounded-xl text-[10px] text-blue-700 dark:text-blue-300"><div className="font-bold mb-0.5">링크 미리보기</div><div className="text-[9px] text-blue-500">vibe.ui.kr</div></div>;
  if (id === 'COMM-08') return <div className="flex items-center gap-2 px-3 py-2 bg-blue-600 text-white rounded-2xl rounded-br-sm w-44 text-[10px]"><button className="text-sm">▶</button><div className="flex gap-0.5 items-end h-5">{Array.from({length:12},(_,i)=><div key={i} style={{height:`${20+Math.random()*60}%`}} className="w-1 bg-white/70 rounded-full" />)}</div><span className="text-white/70">0:24</span></div>;
  if (id === 'COMM-09') return <div className="flex items-center gap-2 w-full"><div className="flex-1 h-px bg-gray-200 dark:bg-gray-700" /><span className="text-[9px] text-gray-400 whitespace-nowrap">오늘</span><div className="flex-1 h-px bg-gray-200 dark:bg-gray-700" /></div>;
  if (id === 'COMM-10') return <div className="w-full bg-white dark:bg-gray-800 border rounded-xl overflow-hidden text-[10px]"><div className="flex items-center gap-2 px-3 py-2 bg-gray-50 dark:bg-gray-900"><span className="text-sm">💬</span><span className="font-bold text-gray-700 dark:text-gray-300">카카오톡</span><span className="bg-red-500 text-white px-1 rounded-full text-[9px]">5</span><span className="ml-auto text-gray-400">▼</span></div></div>;

  // ===== COMMERCE =====
  if (id === 'ECOM-01') return <div className="w-full bg-white dark:bg-gray-800 border rounded-xl p-2 text-[10px]"><div className="w-full h-10 bg-gray-100 dark:bg-gray-700 rounded-lg mb-1" /><div className="font-bold text-gray-800 dark:text-gray-200">상품명</div><div className="text-blue-600 font-bold">₩29,000</div></div>;
  if (id === 'ECOM-02') return <div className="w-full flex items-center gap-2 p-2 bg-white dark:bg-gray-800 border rounded-xl text-[10px]"><div className="w-6 h-6 bg-gray-100 dark:bg-gray-700 rounded" /><div className="flex-1 text-gray-700 dark:text-gray-300 font-semibold">상품 × 2</div><div className="font-bold text-blue-600">₩58,000</div></div>;
  if (id === 'ECOM-03') return <button className="p-1.5 rounded-xl border border-gray-200 dark:border-gray-700 text-gray-400 hover:text-red-500 transition-colors"><Heart className="w-4 h-4" /></button>;
  if (id === 'ECOM-04') return <div className="flex items-center gap-1.5"><div className="w-2 h-2 rounded-full bg-green-500" /><span className="text-[10px] font-bold text-green-600">재고 충분</span><span className="text-[10px] text-gray-400">(47개)</span></div>;
  if (id === 'ECOM-05') return <div className="w-full flex gap-1.5"><input readOnly value="SAVE20" className="flex-1 px-2 py-1 border rounded-lg text-[10px] bg-white dark:bg-gray-800 text-gray-700 dark:text-gray-300" /><span className="px-2 py-1 bg-blue-600 text-white rounded-lg text-[10px] font-bold">적용</span></div>;
  if (id === 'ECOM-06') return <div className="w-full p-2 bg-white dark:bg-gray-800 border rounded-xl text-[10px]"><div className="flex justify-between text-gray-500"><span>원가</span><span className="line-through">₩50,000</span></div><div className="flex justify-between font-bold"><span className="text-red-500">-20%</span><span className="text-blue-600">₩40,000</span></div></div>;
  if (id === 'ECOM-07') return <div className="flex items-center gap-1 text-[10px]"><div className="text-amber-400">★★★★☆</div><span className="text-gray-600 dark:text-gray-400 font-bold">4.2</span><span className="text-gray-400">(128)</span></div>;
  if (id === 'ECOM-08') return <div className="w-full flex items-center gap-2 p-2 bg-blue-50 dark:bg-blue-950 border border-blue-200 dark:border-blue-900 rounded-xl text-[10px]"><span>🚚</span><span className="text-blue-700 dark:text-blue-400 font-semibold">내일 도착 예정</span></div>;
  if (id === 'ECOM-09') return <div className="w-full p-2 bg-white dark:bg-gray-800 border rounded-xl text-[10px]"><div className="text-gray-500 mb-1">상품 비교</div><div className="grid grid-cols-2 gap-1"><div className="bg-gray-50 dark:bg-gray-700 rounded p-1 text-gray-600 dark:text-gray-400">A 상품</div><div className="bg-gray-50 dark:bg-gray-700 rounded p-1 text-gray-600 dark:text-gray-400">B 상품</div></div></div>;
  if (id === 'ECOM-10') return <div className="flex items-center gap-2 px-3 py-1.5 bg-red-500 text-white rounded-xl text-[10px] font-bold"><span>⚡</span><span className="font-mono">01:23:45</span></div>;
  if (id === 'ECOM-11') return <div className="flex gap-1.5 flex-wrap justify-center">{['S','M','L','XL'].map((s,i) => <button key={s} className={`px-2 py-1 rounded-lg border text-[10px] font-bold ${i===1?'bg-gray-900 text-white border-gray-900':'border-gray-300 dark:border-gray-600 text-gray-600 dark:text-gray-400'}`}>{s}</button>)}</div>;
  if (id === 'ECOM-12') return <div className="flex gap-2 overflow-hidden">{[1,2,3].map(i => <div key={i} className="flex-shrink-0 w-12 h-12 bg-gray-100 dark:bg-gray-800 rounded-xl border" />)}</div>;
  if (id === 'ECOM-13') return <div className="w-full p-2 bg-white dark:bg-gray-800 border rounded-xl text-[10px]"><div className="flex items-center gap-1 mb-1"><span className="text-xs">🎁</span><span className="font-bold text-orange-600">번들 -20%</span></div><div className="text-gray-500">3개 상품 ₩38,000</div></div>;
  if (id === 'ECOM-14') return <div className="w-full flex flex-col gap-1 text-[10px]"><div className="flex items-center gap-2"><div className="w-3 h-3 rounded-full bg-green-500 flex items-center justify-center"><span className="text-white text-[7px]">✓</span></div><span className="text-gray-600 dark:text-gray-400">결제 완료</span></div><div className="ml-1.5 w-0.5 h-3 bg-gray-200 dark:bg-gray-700" /><div className="flex items-center gap-2"><div className="w-3 h-3 rounded-full border-2 border-blue-500 animate-pulse" /><span className="text-blue-600 font-bold">배송 중</span></div></div>;
  if (id === 'ECOM-15') return <div className="w-full p-2 bg-gradient-to-r from-blue-600 to-indigo-700 text-white rounded-xl text-[10px]"><div className="text-[9px] opacity-70">내 포인트</div><div className="text-lg font-black">12,450<span className="text-sm font-semibold ml-0.5 opacity-70">P</span></div></div>;

  // ===== CHARTS =====
  if (id === 'CHART-01') return <div className="flex items-end gap-1 h-10 w-full px-2">{[60,80,45,90,70,55,85].map((h,i)=><div key={i} style={{height:`${h}%`}} className={`flex-1 rounded-t-sm ${i===3?'bg-blue-600':'bg-blue-300 dark:bg-blue-800'}`} />)}</div>;
  if (id === 'CHART-02') return <svg width="100%" height="40"><polyline points="0,35 30,25 60,30 90,10 120,20 150,5" fill="none" stroke="#3b82f6" strokeWidth="2" strokeLinecap="round" /><polyline points="0,35 30,25 60,30 90,10 120,20 150,5 150,40 0,40" fill="#3b82f6" fillOpacity="0.1" /></svg>;
  if (id === 'CHART-03') return <div className="flex items-center gap-2"><div className="relative w-10 h-10"><svg viewBox="0 0 36 36" className="-rotate-90 w-full h-full"><circle cx="18" cy="18" r="14" fill="none" stroke="#e5e7eb" strokeWidth="4" /><circle cx="18" cy="18" r="14" fill="none" stroke="#3b82f6" strokeWidth="4" strokeDasharray="55 45" /><circle cx="18" cy="18" r="14" fill="none" stroke="#10b981" strokeWidth="4" strokeDasharray="30 70" strokeDashoffset="-55" /></svg></div><div className="text-[9px] space-y-0.5"><div className="flex items-center gap-1"><div className="w-2 h-2 rounded-full bg-blue-500" /><span>A 55%</span></div><div className="flex items-center gap-1"><div className="w-2 h-2 rounded-full bg-green-500" /><span>B 30%</span></div></div></div>;
  if (id === 'CHART-04') return <svg width="100%" height="40"><defs><linearGradient id="g" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#3b82f6" stopOpacity="0.4"/><stop offset="100%" stopColor="#3b82f6" stopOpacity="0"/></linearGradient></defs><path d="M0,35 L30,25 L60,28 L90,10 L120,18 L150,5 L150,40 L0,40 Z" fill="url(#g)"/><polyline points="0,35 30,25 60,28 90,10 120,18 150,5" fill="none" stroke="#3b82f6" strokeWidth="2"/></svg>;

  // ===== AUTH & SECURITY =====
  if (id === 'AUTH-01') return <div className="flex flex-col items-center gap-1"><div className="w-10 h-10 rounded-full bg-blue-50 dark:bg-blue-950 flex items-center justify-center text-2xl border-2 border-blue-200 dark:border-blue-800">👆</div><div className="text-[10px] text-gray-500 font-semibold">지문 인증</div></div>;
  if (id === 'AUTH-02') return <div className="w-full p-2 bg-white dark:bg-gray-800 border rounded-xl text-[10px]"><div className="flex gap-1 mb-1 justify-center">{[0,1,2].map(i=><div key={i} className={`w-5 h-1 rounded-full ${i===0?'bg-blue-600':'bg-gray-200 dark:bg-gray-700'}`}/>)}</div><div className="text-center text-gray-500">QR 스캔 → OTP 입력</div></div>;
  if (id === 'AUTH-03') return <div className="w-full p-2 bg-white dark:bg-gray-800 border rounded-xl text-center text-[10px]"><div className="text-2xl mb-1">📍</div><div className="font-bold text-gray-700 dark:text-gray-300 mb-1">위치 접근</div><div className="flex gap-1 justify-center"><span className="px-2 py-0.5 bg-blue-600 text-white rounded text-[9px]">허용</span><span className="px-2 py-0.5 border rounded text-gray-400 text-[9px]">거부</span></div></div>;
  if (id === 'AUTH-04') return <div className="w-full flex flex-col gap-1"><div className="flex items-center gap-2 px-2 py-1.5 border rounded-lg text-[10px] bg-white dark:bg-gray-800 text-gray-700 dark:text-gray-300 font-semibold"><span className="text-sm">🔵</span>Google로 계속</div><div className="flex items-center gap-2 px-2 py-1.5 bg-black rounded-lg text-[10px] text-white font-semibold"><span className="text-sm">🍎</span>Apple로 계속</div></div>;

  // ===== FORMS =====
  if (id === 'FORMS-01') return <div className="w-full p-2 bg-white dark:bg-gray-800 border rounded-xl text-[10px]"><div className="flex gap-1 mb-2">{[1,2,3].map(s=><div key={s} className={`flex-1 h-1 rounded-full ${s===1?'bg-blue-600':'bg-gray-200 dark:bg-gray-700'}`}/>)}</div><div className="text-gray-500 text-center">1 / 3 단계</div></div>;
  if (id === 'FORMS-02') return <div className="w-full border rounded-xl overflow-hidden text-[10px]"><div className="flex items-center justify-between px-3 py-1.5 bg-gray-50 dark:bg-gray-800 border-b"><span className="font-bold text-gray-700 dark:text-gray-300">초안</span><span className="text-green-600 font-bold">✓ 저장됨</span></div><div className="px-3 py-2 text-gray-400">내용 자동 저장...</div></div>;
  if (id === 'FORMS-03') return <div className="w-full space-y-1 text-[10px]"><input readOnly value="test@email.com" className="w-full px-2 py-1 border-2 border-green-400 bg-green-50 dark:bg-green-950 rounded-lg text-gray-700 dark:text-gray-300" /><div className="text-green-600 font-semibold">✓ 유효한 이메일</div></div>;
  if (id === 'FORMS-04') return <div className="flex gap-1.5 justify-center">{[6,2,4,8,1,9].map((n,i)=><div key={i} className={`w-6 h-8 border-2 rounded-lg flex items-center justify-center text-xs font-bold ${i<4?'border-blue-500 bg-blue-50 dark:bg-blue-950 text-blue-600':'border-gray-200 dark:border-gray-700 text-gray-700 dark:text-gray-300'}`}>{n}</div>)}</div>;

  // ===== ACCESSIBILITY =====
  if (id === 'A11Y-01') return <div className="w-full p-2 border-2 border-blue-500 rounded-xl text-[10px] text-center"><div className="text-[9px] text-gray-400 mb-0.5">Tab 포커스 트랩</div><div className="flex justify-center gap-2"><button className="px-2 py-0.5 border border-blue-500 rounded text-blue-600 text-[9px] ring-2 ring-blue-300">취소</button><button className="px-2 py-0.5 bg-blue-600 text-white rounded text-[9px]">확인</button></div></div>;
  if (id === 'A11Y-02') return <div className="w-full p-2 bg-gray-50 dark:bg-gray-800 border rounded-xl text-[10px]"><div className="text-gray-400 mb-1 text-[9px]">aria-live region</div><div className="bg-white dark:bg-gray-900 border rounded-lg px-2 py-1 font-mono text-gray-500 text-[9px]">저장이 완료됐습니다</div></div>;

  // ===== AI/ML UX =====
  if (id === 'AI-01') return <div className="flex gap-2 items-start w-full"><div className="w-5 h-5 rounded-full bg-gradient-to-br from-violet-600 to-blue-600 flex items-center justify-center text-white text-[7px] font-bold flex-shrink-0">AI</div><div className="bg-gray-100 dark:bg-gray-800 rounded-2xl rounded-tl-sm px-2 py-1.5 text-[10px] text-gray-700 dark:text-gray-300">안녕하세요! 무엇을 도와드릴까요?<span className="inline-block w-0.5 h-3 bg-gray-500 ml-0.5 animate-pulse align-text-bottom" /></div></div>;
  if (id === 'AI-02') return <div className="flex gap-2 items-start w-full"><div className="w-5 h-5 rounded-full bg-gradient-to-br from-violet-600 to-blue-600 flex items-center justify-center text-white text-[7px] font-bold flex-shrink-0">AI</div><div className="bg-gray-100 dark:bg-gray-800 rounded-2xl rounded-tl-sm px-3 py-2 flex items-center gap-1">{[0,1,2].map(i=><span key={i} style={{animationDelay:`${i*150}ms`}} className="w-1.5 h-1.5 bg-gray-400 rounded-full animate-bounce block" />)}</div></div>;
  if (id === 'AI-03') return <div className="w-full border-2 border-gray-200 dark:border-gray-700 rounded-2xl p-2 text-[10px]"><div className="text-gray-400 mb-2">AI에게 무엇이든 물어보세요...</div><div className="flex justify-end"><div className="w-6 h-6 bg-blue-600 rounded-xl flex items-center justify-center text-white text-xs">↑</div></div></div>;
  if (id === 'AI-04') return <div className="flex flex-col gap-1.5"><div className="inline-flex items-center gap-2 px-2 py-1 bg-green-100 dark:bg-green-950 rounded-full"><div className="w-10 h-1.5 bg-green-500 rounded-full" /><span className="text-[10px] font-bold text-green-700 dark:text-green-400">94% · 높음</span></div><div className="inline-flex items-center gap-2 px-2 py-1 bg-yellow-100 dark:bg-yellow-950 rounded-full"><div className="w-6 h-1.5 bg-yellow-500 rounded-full" /><span className="text-[10px] font-bold text-yellow-700 dark:text-yellow-400">62% · 보통</span></div></div>;
  if (id === 'AI-05') return <div className="w-full text-[10px]"><div className="text-gray-700 dark:text-gray-300 mb-1">AI 답변 내용<sup className="text-[8px] text-blue-600 font-bold">①</sup></div><div className="flex items-start gap-1.5 p-1.5 border rounded-xl bg-gray-50 dark:bg-gray-800"><span className="w-4 h-4 bg-blue-600 text-white text-[8px] font-bold rounded-full flex items-center justify-center flex-shrink-0">1</span><div><div className="font-semibold text-gray-700 dark:text-gray-300">출처 제목</div><div className="text-gray-400">vibe.ui.kr</div></div></div></div>;

  // ===== MEDIA =====
  if (id === 'MEDIA-01') return <div className="w-full bg-gray-900 rounded-xl p-2 text-white text-[10px]"><div className="w-full h-8 bg-gray-700 rounded mb-2 flex items-center justify-center text-gray-500 text-xs">▶ 비디오</div><div className="flex items-center gap-2"><span>⏸</span><div className="flex-1 h-1 bg-gray-600 rounded-full"><div className="w-1/3 h-full bg-blue-500 rounded-full" /></div><span>1:23</span><span>⛶</span></div></div>;
  if (id === 'MEDIA-02') return <div className="grid grid-cols-3 gap-1 w-full">{[1,2,3,4,5,6].map(i=><div key={i} className={`aspect-square rounded-lg ${i===1?'ring-2 ring-blue-500':''} bg-gradient-to-br from-gray-200 to-gray-300 dark:from-gray-700 dark:to-gray-800`} />)}</div>;
  if (id === 'MEDIA-03') return <div className="w-full flex items-center gap-2 bg-white dark:bg-gray-800 border rounded-xl p-2 text-[10px]"><div className="w-8 h-8 bg-gray-100 dark:bg-gray-700 rounded-lg flex items-center justify-center text-sm flex-shrink-0">🎵</div><div className="flex-1 min-w-0"><div className="font-bold text-gray-800 dark:text-gray-200 truncate">트랙 제목</div><div className="w-full h-1 bg-gray-200 dark:bg-gray-700 rounded-full mt-1"><div className="w-2/5 h-full bg-blue-500 rounded-full" /></div></div><button className="w-7 h-7 bg-blue-600 text-white rounded-full flex items-center justify-center text-xs flex-shrink-0">▶</button></div>;

  // Category-based fallback for any unregistered IDs
  const categoryColors: Record<string, string> = {
    'Actions': 'from-blue-500 to-blue-600',
    'Input': 'from-indigo-500 to-indigo-600',
    'Selection': 'from-violet-500 to-violet-600',
    'Navigation': 'from-cyan-500 to-cyan-600',
    'Overlay': 'from-slate-500 to-slate-600',
    'Feedback & States': 'from-emerald-500 to-emerald-600',
    'Gesture': 'from-pink-500 to-pink-600',
    'Motion': 'from-purple-500 to-purple-600',
    'Patterns': 'from-amber-500 to-amber-600',
    'Data Display': 'from-teal-500 to-teal-600',
    'Charts': 'from-blue-600 to-indigo-700',
    'Commerce': 'from-orange-500 to-orange-600',
    'Communication': 'from-rose-500 to-rose-600',
    'Layout': 'from-fuchsia-500 to-fuchsia-600',
    'Auth & Security': 'from-red-600 to-red-700',
    'Forms': 'from-lime-500 to-lime-600',
    'Accessibility': 'from-sky-500 to-sky-600',
    'AI/ML UX': 'from-violet-600 to-purple-700',
    'Media': 'from-gray-600 to-gray-700',
  };
  const gradient = categoryColors[category] || 'from-gray-500 to-gray-600';
  return (
    <div className={`w-full py-2 px-3 bg-gradient-to-r ${gradient} text-white rounded-xl text-xs font-semibold flex items-center gap-2`}>
      <Sparkles className="w-3.5 h-3.5 flex-shrink-0" />
      <span className="truncate">{name}</span>
    </div>
  );
};
